services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/ecommerce
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      - db
      - redis
    volumes:
      - ./prisma:/app/prisma

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8081:80'
    depends_on:
      - db
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  db_data:
