services:
#  backend:
#   build: ./backend
#   ports:
#   - "8080:80"
#   environment:
#   - DB_HOST=db
#   - REDIS_HOST=redis
#   depends_on:
#   - db
#   - redis
 
 
 db:
  image: mysql:8
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: ecommerce
  ports:
    - "3306:3306"
  volumes:
  - db_data:/var/lib/mysql
 
 redis:
  image: redis:alpine
  ports:
  - "6379:6379"
 
 phpmyadmin:
  image: phpmyadmin
  ports:
  - "8081:80"
 
volumes:
 db_data: