services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=mysql://root:root@db:3306/ecommerce
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./prisma:/app/prisma

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test:
        ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-proot']
      timeout: 20s
      interval: 10s
      retries: 10
      start_period: 40s

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      timeout: 3s
      interval: 5s
      retries: 5
      start_period: 10s

  phpmyadmin:
    image: phpmyadmin
    ports:
      - '8081:80'
    depends_on:
      db:
        condition: service_healthy
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306

volumes:
  db_data:
